function [tau,F] = get_spring_torque(q,Ks,in3)
%GET_SPRING_TORQUE
%    [TAU,F] = GET_SPRING_TORQUE(Q,Ks,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    17-Jul-2025 12:45:37

l0 = in3(1,:);
l1 = in3(2,:);
l2 = in3(3,:);
l3 = in3(4,:);
l4 = in3(5,:);
l5 = in3(6,:);
l6 = in3(7,:);
t2 = cos(q);
t3 = sin(q);
t4 = l1+l4;
t5 = l2.^2;
t7 = l0.*1.0e+3;
t8 = l3.*1.0e+3;
t9 = l6.*1.0e+3;
t6 = t2.*t4;
t10 = -t8;
t13 = t3.*t4.*1.0e+3;
t11 = -t6;
t12 = l5+t11;
t14 = t12.^2;
t15 = -t14;
t16 = t5+t15;
t17 = sqrt(t16);
t18 = t17.*1.0e+3;
t19 = t7+t9+t10+t13+t18;
t20 = exp(t19);
t21 = t20+1.0;
t22 = log(t21);
tau = (Ks.*t20.*t22.*(t6.*1.0e+3-(t3.*t4.*t12.*1.0e+3)./t17))./(t21.*1.0e+6);
if nargout > 1
    F = (Ks.*t22)./1.0e+3;
end
end
